// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcr2tCaGL5qtXdO6ru8sdsS-QqSHd4nFs',
    appId: '1:370279495213:web:cc97d2a6e09334d5d9eaa4',
    messagingSenderId: '370279495213',
    projectId: 'sharberry-shop-86867',
    authDomain: 'sharberry-shop-86867.firebaseapp.com',
    storageBucket: 'sharberry-shop-86867.appspot.com',
    measurementId: 'G-Y89ZVLQHH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-qlHfXvLMK1a6McWw0ETq4w3Gu40mR34',
    appId: '1:370279495213:android:165d29bb1e24d790d9eaa4',
    messagingSenderId: '370279495213',
    projectId: 'sharberry-shop-86867',
    storageBucket: 'sharberry-shop-86867.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmnFN4qD97ZXUtOptAKSefx1Q_TKw1wLI',
    appId: '1:370279495213:ios:a617fa286414b6d7d9eaa4',
    messagingSenderId: '370279495213',
    projectId: 'sharberry-shop-86867',
    storageBucket: 'sharberry-shop-86867.appspot.com',
    androidClientId: '370279495213-i7jll33pqchh7k9kvaf35fkkp8a8va80.apps.googleusercontent.com',
    iosClientId: '370279495213-hsirbtq9evsntqtno144afnr68mpm3u7.apps.googleusercontent.com',
    iosBundleId: 'com.example.sharberryShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmnFN4qD97ZXUtOptAKSefx1Q_TKw1wLI',
    appId: '1:370279495213:ios:84966a89ce7ddbf1d9eaa4',
    messagingSenderId: '370279495213',
    projectId: 'sharberry-shop-86867',
    storageBucket: 'sharberry-shop-86867.appspot.com',
    androidClientId: '370279495213-i7jll33pqchh7k9kvaf35fkkp8a8va80.apps.googleusercontent.com',
    iosClientId: '370279495213-t0avtg51o36rj0vcjhavb21hd7ma0u7r.apps.googleusercontent.com',
    iosBundleId: 'com.example.sharberryShop.RunnerTests',
  );
}
